const GET_CHARACTERS = "GET_CHARACTERS";
const GET_CHARACTER_BY_ID = "GET_CHARACTER_BY_ID";
const CLEAR_CHARACTERS = "CLEAR_CHARACTERS";
const CLEAR_CHARACTER_BY_ID = "CLEAR_CHARACTER_BY_ID";
const SET_ERROR = "SET_ERROR";
const LOADING = "LOADING";

export {
  GET_CHARACTERS,
  GET_CHARACTER_BY_ID,
  CLEAR_CHARACTERS,
  CLEAR_CHARACTER_BY_ID,
  SET_ERROR,
  LOADING,
};
